### ISSUE TITLE
음성인식을 통한 술게임을 만들어주세요.

### ISSUE THREAD

**Issue by HongKiBum** [HongKiBum/Alcohol_Total_Game#2]
사용자에게 음성파일을 받아 문장 정확도를 검사해 사용자의 취한정도를 파악하는 게임을 만들어주세요.

**Comment by mingue122** [comment]
발음하기 어려운 문장들을 모아서 랜덤으로 문장 나오게 만드러드렸습니다. 발음파일을 저장하고 업로드해보세요.
