### ISSUE TITLE
사용자의 손 모양 분석으로 랜덤한 사람이 벌칙에 당첨되는 코드를 작성해주세요.

### ISSUE THREAD

**Issue by HongKiBum** [HongKiBum/Alcohol_Total_Game#3]
사용자에게 벌칙과 사진을 받아, 그 사진 속 사용자들의 손 모양을 분석하고 그 중 랜덤한 손 모양 하나를 골라 그 손 모양을 하는 사람들이  벌칙을 받는 게임을 만들어주세요.

**Comment by sanghuicho** [comment]
제가 만들어 볼게요!!
